### ISSUE TITLE
a plugin for virtools 4.0

### ISSUE THREAD

**Issue by gamemasterzen** [yyc12345/vtobjplugin#2]
i wish you could make a obj importer to virtools 4.0
i have only virtools 4.0

**Comment by yyc12345** [comment]
I think this project is fully compatible with virtools 4.0. so the exporter is easily gotten if you have proper SDK and compile environment.
also, I will provide a binary exporter in Release page **after a few days**. I need to add a new configurations for this solution.

**Comment by yyc12345** [comment]
problem solved.
now there are 3 versions of this plugin(vt35, vt4, vt5) which can be downloaded from Release page.
