### ISSUE TITLE
Virtools 5 SDK

### ISSUE THREAD

**Issue by rich-gg** [yyc12345/vtobjplugin#6]
Hi

I'm going to try and build the exporter on virtools 5, because I'm trying to export an old Virtools project.
Would you have an old Virtools 5 SDK somewhere ?

**Comment by rich-gg** [comment]
ooops, I asked to soon
The Sdk folder is in the Virtools 5 Folder in Programs :)
I got the plugin to compile and to run on v5 ! 
(Just need to know from my 3Ds max friend if the file is ok)

**Comment by yyc12345** [comment]
It seems that the problem already have been resolved.
btw, some pre-compiled binary plugins already have been put in Release page of this project and you can download them directly. These binary plugins support Virtools 3.5, 4.0 and 5.0. I think this will cover most usage scenarios.
